version: '3'

services:
  autoinfo-mongodb-srv:
    hostname: mongodb
    container_name: autoinfo-mongodb
    image: mongo
    restart: always
    ports:
      - 27022:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_AUTH_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_AUTH_DATABASE}
